---
- name: Set splunk path
  set_fact:
    splunk_home: /opt/splunk

- name: Adding splunk the path in the bashrc files
  become: yes
  lineinfile: 
    dest: /etc/profile
    line: 'export SPLUNK_HOME={{ splunk_home }}' 
    insertafter: 'EOF'     
    state: present

- name: Source the bashrc file  
  shell: "source /etc/profile"

- name: Install splunk
  become: yes
  unarchive:
    src: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.1&product=splunk&filename=splunk-7.0.1-2b5b15c4ee89-Linux-x86_64.tgz&wget=true
    dest: /opt
    remote_src: yes

- name: Start splunk
  become: yes
  shell: "{{ splunk_home }}/bin/splunk start --accept-license"  

- name: Enable auto-start
  become: yes
  shell: "{{ splunk_home }}/bin/splunk enable boot-start" 

- name: Reset Splunk password
  become: yes
  shell: "{{ splunk_home }}/bin/splunk edit user admin -password '{{ splunk_pwd }}' -role admin"
  ignore_errors: True